[build]
  command = "pip install -r requirements.txt"
  publish = "public"

[build.environment]
  PYTHONUNBUFFERED = "1"
  PIP_NO_CACHE_DIR = "off"
  PIP_DISABLE_PIP_VERSION_CHECK = "on"
  PIP_DEFAULT_TIMEOUT = "100"
